# Generated by Django 3.2.15 on 2022-08-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=14),
            preserve_default=False,
        ),
    ]
