# Generated by Django 3.2.15 on 2022-09-01 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0003_house_endereco'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='endereco',
        ),
        migrations.AlterField(
            model_name='house',
            name='created_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
