# Generated by Django 3.2.15 on 2022-09-01 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_alter_house_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
