# Generated by Django 3.2.15 on 2022-09-01 00:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0007_auto_20220831_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='house',
            name='descricao',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='house',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='house',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
