# Generated by Django 3.2.15 on 2022-09-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0008_auto_20220831_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='descricao',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
