# Generated by Django 3.2.15 on 2022-09-01 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0010_alter_house_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='titulo',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
