# Generated by Django 3.2.15 on 2022-09-03 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0013_auto_20220831_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='bairro',
            field=models.CharField(default='Centro', max_length=40),
        ),
        migrations.AddField(
            model_name='house',
            name='cidade',
            field=models.CharField(default='São Raimundo Nonato', max_length=40),
        ),
        migrations.AlterField(
            model_name='house',
            name='imagem',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
